name: tock-hw-ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: [self-hosted]

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: source ~/tock-test-harness/runner-build.sh
    - name: Test Flash
      run: echo "test"
      
  install:
    
    runs-on: [self-hosted]
    
    steps:
    - name: Install
      run: source ~/tock-test-harness/runner-flash.sh
      
  
