name: tock-hw-ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: [self-hosted]

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: python3 ~/tock-test-harness/runner_build.py
      
  install:
    
    runs-on: [self-hosted]
    
    steps:
    - name: Install
      run: python3 ~/tock-test-harness/runner_init.py
      
  
