name: tock-hw-ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: [self-hosted]

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
      
  hello:
    name: hello
    runs-on: [self-hosted]
    steps:
    - id: step1
      run: echo "hello world"
